### PR TITLE
Apple Clone page Review

### PR DESCRIPTION
**Pull request by MFahadUmer**
project name
## Building with Backgrounds and Gradients
in this project I learn how to:
-work with background images
-work with gradients

### CODE REVIEW

**Comment by MFahadUmer** [comment]
Resolve all Linters check
validated by using validator (HTML and CSS)

**Comment by SevlaMare** [comment]
### Html semantic
-Use tag <main> instead of class="main"
-Always try to use one and just one <h1> for each web page.
Using semantic will have a nice CEO.

### Navbar
-Check the border on hover, of most left and right links.

### Grid (The 4 pictures in a row)
-The max-width is overflowing.

### Footer
-Can have some margin between the links.
-The flag icon should have a vertical align on center (Can be done with a single flex attribute).
-Should always have only two lines (Shop the Apple Online... is warping).

### On readme file (Optional)
-Nice too have requirements section.
-From (Open a web browser) to (Run index.html file)
seems weird, they are all like titles stuck together.
-Acknowledgments, can save that section to indicate a specific person or group, instead of widespread.

**Comment by adaorachi** [comment]
👋 Hi @MFahadUmer 

Well done on the completion of the first draft of this project. 💪 Your project view looks very good. 💯👍  The navbar and images are well aligned and positioned where it should be. 👏 
In all, you did a fantastic job on this but there are a couple of things you'll need to fix to make your project look very professional. 
So hang in there, you are just a step away from completing this project. ☺️ 💪 

---
### **CHANGES REQUIRED**
---

- [x] First, your commit messages are not meaningful enough. Ensure you write very good commit messages that explicitly describe what you have done in the project before the commit. Check this link to see how to write professional commit messages - [Professional commit messages from Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) and make use of this practice in this project and future ones.
---

- [x] Your README looks okay but you can still improve on it to make it look better. The description of your project should contain what your project is all about. What you achieved in the project and what you enjoyed doing in the project. It should have at least a paragraph.  **You only have a one-line sentence in it. You should consider fixing that.**
apple22

***
Also, you should improve the installation process. You should always have in mind that other persons who will make use of your repo could be non-techy. So, make your installation process more explanatory. Like showing the terminal command for cloning your project and using it - `git clone https://github.com/MFahadUmer/apple` , `cd apple`, `open localhost on your web browser `.

apple33

---

- [x] I am assuming the other comments by @SevlaMare are for the peer-to-peer code reviews from your stand-up team (Refer to screenshot below). So if that's the case, then those comments **are not** supposed to be in your Pull Request. They should be in an issue. Kindly ask the owner of the comment to delete the comments here and instead create an issue for those comments.

apple2

---

- [x] The four elements with images on the bottom should be links. So, ensure you have an anchor tag enclosed around each of them.

apple222

---

The requirement below is **NOT CONSIDERED** to be mandatory. But I strongly encourage you to take a look at it because it will come in handy in future projects.

---

- [ ] [**optional**] For the line dividers you have in between each link (shown in the screenshot below), you should consider using a pseudo-css-elements like `::before` or  `::after`, instead of putting them in `<li>` tags. They are very helpful in creating content like that. See this link for better knowledge [Pseudo Element](https://developer.mozilla.org/en-US/docs/Web/CSS/::before).

apple2222

---

### **After implementing the changes highlighted above, request for another review by submitting a Code Review Form.** 

Should you have any questions or need any help, please feel free to reach out to me on Slack(@adaorachi). ☺️ 

**Happy Coding and Good-luck on it.**

**MaryAnn Chukwuka**

**Comment by MFahadUmer** [comment]
## I was asked to solve the commits problem 
image
the issue was there I was not able to link the stickler. ci file that's why I was just trying to fix this issue and didn't care for the commits.
### the 2nd issue was with a readme file
image
I've just improved the read me file.

### the third issue was the comments
image
these comments are from my mentor and I asked him to delete these comments so this issue is solved too.

### the fourth issue was I'm the images
image
I 've changed these images into links.

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :1st_place_medal: :fireworks: 

Hi @MFahadUmer :smile: :smile: 

Congrats for the hard work, :100: your page looks beautiful and professional,  your pr is also great  :fireworks: 

you did the required changes asked by MaryAnn and your project was approved :fireworks:  :fireworks: :fireworks: :fireworks: 

### **SUGGESTION FOR THE NEXT PROJECTS:**

:v:  You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''youtube-page'' instead of ''feature's', for example. It will be more descriptive. :+1: :+1: 


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next project!!!**

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
